# -------------------- PATHS -------------------- #
paths:
  raw_data: "data/preprocessed_data/cleaned_student_dataset.csv"
  processed_dir: "artifacts/processed"
  preprocessor_file: "artifacts/processed/preprocessor.pkl"
  log_file: "artifacts/logs/preprocessing.log"

# -------------------- SPLIT SETTINGS -------------------- #
split:
  test_size: 0.2
  random_state: 42
  stratify: true

# -------------------- COLUMNS -------------------- #
columns:
  target: "Target"
  drop: ["Target", "id"]
  categorical: ["Displaced", "Debtor", "Tuition fees up to date", "Gender", "Scholarship holder"]

# -------------------- IMPUTATION SETTINGS -------------------- #
imputation:
  numeric_strategy: "median"
  categorical_strategy: "most_frequent"
