name: Auto Retrain Models

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'data/new_data/new_student_data.csv'

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data versioning and retraining
        run: |
          python src/data_version_and_retrain.py

      - name: Upload trained models
        uses: actions/upload-artifact@v3
        with:
          name: trained-models
          path: artifacts/models/
