name: Auto Retrain Models

on:
  push:
    branches:
      - dev
    paths:
      - 'data/new_data/new_student_data.csv'

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Run data versioning, preprocessing & training
      - name: Run retraining pipeline
        run: python src/data_version_and_retrain.py

      # 5️⃣ Upload trained models
      - name: Upload trained models
        uses: actions/upload-artifact@v4
        with:
          name: trained-models
          path: artifacts/models/

      # 6️⃣ Upload metrics/logs (optional)
      - name: Upload training logs and metrics
        uses: actions/upload-artifact@v4
        with:
          name: training-logs
          path: |
            artifacts/logs/
            artifacts/training_metrics.json
